In [3]:
import tensorflow as tf
import numpy as np #배열 처리를 위해 사용
from pandas.io.parsers import read_csv #엑셀 데이터를 읽어오기 위해 필요

In [4]:

#메모장으로 키면 , 으로 분리되어있기 때문 (csv파일이기 때문)
data = read_csv('../lol_data/total_4.csv', sep=',') # '를 토큰으로 데이터를 분리해서 담을수 있도록 
#print(data)

#정수형도 소수점형태로 받아와야한다.
xy = np.array(data, dtype=np.float32) #행렬 형태로 해당 데이터를 담을 수 있도록 함

In [5]:
print(xy)

[[ 1.0500e+02  1.3500e+02  2.7000e+01 ...  4.0000e+01  1.3400e+02
  -7.6190e+03]
 [ 1.0000e+02  2.8000e+01  1.0000e+00 ...  4.0000e+01  3.9000e+01
   1.2059e+04]
 [ 1.1600e+02  2.3000e+01  1.0000e+00 ...  1.1700e+02  5.7000e+01
   8.8800e+03]
 ...
 [ 1.0500e+02  2.3000e+01  1.3200e+02 ...  1.1700e+02  8.0000e+00
   1.0879e+04]
 [ 2.0000e+00  8.3000e+01  1.3200e+02 ...  1.2000e+02  1.3100e+02
   9.5730e+03]
 [ 1.1300e+02  1.1000e+01  1.3200e+02 ...  7.6000e+01  3.9000e+01
   5.7940e+03]]


In [6]:
#10개의 변인을 입력을 받습니다.
x_data = xy[:,0:-1] # 10가지 챔피언정보

#가격 값을 입력 받습니다.
y_data = xy[:,[-1]] # 글로벌 골드

In [7]:
print(y_data)

[[-7619.]
 [12059.]
 [ 8880.]
 ...
 [10879.]
 [ 9573.]
 [ 5794.]]


In [2]:
X = tf.placeholder(tf.float32, shape=[None,10], name="cham") #10개의 변인이 담길수 있게
Y = tf.placeholder(tf.float32, shape=[None,1], name="gold")

#배열 형식의 난수 만들기
W = tf.Variable(tf.random_normal([10,1]), name="weight") #가중치
b = tf.Variable(tf.random_normal([1]), name="bias") #bias 값

In [6]:
#기본적으로 선형 회귀같은 경우는 행렬의 곱 연산을 이용해서 결과식을 세울수 있다.
#가설식 하이포테시스
# M행 K열 / K행 M열
# 행렬의 곱은 K열과 K행이 같아야 성립할 수 있다.
# 같아야 두 식이 이어질수가 있어서 곱셈이 가능하다.
# 앞에서는 행이 필요하고 뒤에서는 열이 필요하다
# 행렬의 곱셈은 곱셈의 결과의 해석이 중요하다.
# https://www.youtube.com/watch?v=qwEWO-cQwXQ

#학생들이 햄버거를 살때 낼 돈을 표라는 그래프로 나타낸것! (가격과, 살 갯수를 연결시켜 놓은 것)
hypothesis = tf.matmul(X,W, name="operation") +b 

In [7]:
#비용함수
#우리가 세운 가설이 얼마나 정확한지 판단하는 기준
#데이터와 가설의 직선거리를 계산해서 판단함
cost = tf.reduce_mean(tf.square(hypothesis-Y), name="result")

In [8]:
#최적화 함수
#학습의 보폭을 적절히 선택해야 안정적인 학습이 가능하다.
#0.000005
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.000005,name="opt") #학습률 정도(매우 중요)
train = optimizer.minimize(cost,name="tra") #훈련 설정

In [9]:
#세션을 만들어야 학습을 시킬수 있음 (계산을 한다.)
sess = tf.Session()
#변수를 초기화해줘야 변수 대입이 된다.
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(1000001):
    cost_, hypo_, _ = sess.run([cost,hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 500 == 0:
        print("#", step, " 손실 비용: ", cost_)
        print("- 배추 가격: ",hypo_[0])#예측되고 있는 배추 가격 #첫번째 데이터에 대해서

# 0  손실 비용:  89709390.0
- 배추 가격:  [142.84319]
# 500  손실 비용:  80515990.0
- 배추 가격:  [-4166.432]
# 1000  손실 비용:  80514290.0
- 배추 가격:  [-4190.4224]
# 1500  손실 비용:  80514270.0
- 배추 가격:  [-4191.1636]
# 2000  손실 비용:  80514240.0
- 배추 가격:  [-4191.204]
# 2500  손실 비용:  80514210.0
- 배추 가격:  [-4191.221]
# 3000  손실 비용:  80514190.0
- 배추 가격:  [-4191.238]
# 3500  손실 비용:  80514160.0
- 배추 가격:  [-4191.254]
# 4000  손실 비용:  80514130.0
- 배추 가격:  [-4191.2705]
# 4500  손실 비용:  80514110.0
- 배추 가격:  [-4191.2866]
# 5000  손실 비용:  80514080.0
- 배추 가격:  [-4191.303]
# 5500  손실 비용:  80514060.0
- 배추 가격:  [-4191.3203]
# 6000  손실 비용:  80514030.0
- 배추 가격:  [-4191.3354]
# 6500  손실 비용:  80514020.0
- 배추 가격:  [-4191.353]
# 7000  손실 비용:  80513976.0
- 배추 가격:  [-4191.3687]
# 7500  손실 비용:  80513950.0
- 배추 가격:  [-4191.3853]
# 8000  손실 비용:  80513940.0
- 배추 가격:  [-4191.402]
# 8500  손실 비용:  80513900.0
- 배추 가격:  [-4191.419]
# 9000  손실 비용:  80513870.0
- 배추 가격:  [-4191.434]
# 9500  손실 비용:  80513860.0
- 배추 가격:  [-4191.451]
# 10000  손실 비용: 

# 82000  손실 비용:  80510180.0
- 배추 가격:  [-4193.812]
# 82500  손실 비용:  80510140.0
- 배추 가격:  [-4193.828]
# 83000  손실 비용:  80510130.0
- 배추 가격:  [-4193.8447]
# 83500  손실 비용:  80510104.0
- 배추 가격:  [-4193.86]
# 84000  손실 비용:  80510070.0
- 배추 가격:  [-4193.8765]
# 84500  손실 비용:  80510050.0
- 배추 가격:  [-4193.893]
# 85000  손실 비용:  80510024.0
- 배추 가격:  [-4193.9087]
# 85500  손실 비용:  80510000.0
- 배추 가격:  [-4193.926]
# 86000  손실 비용:  80509976.0
- 배추 가격:  [-4193.9414]
# 86500  손실 비용:  80509944.0
- 배추 가격:  [-4193.958]
# 87000  손실 비용:  80509920.0
- 배추 가격:  [-4193.974]
# 87500  손실 비용:  80509900.0
- 배추 가격:  [-4193.9897]
# 88000  손실 비용:  80509880.0
- 배추 가격:  [-4194.0054]
# 88500  손실 비용:  80509860.0
- 배추 가격:  [-4194.023]
# 89000  손실 비용:  80509816.0
- 배추 가격:  [-4194.0376]
# 89500  손실 비용:  80509800.0
- 배추 가격:  [-4194.0557]
# 90000  손실 비용:  80509780.0
- 배추 가격:  [-4194.0713]
# 90500  손실 비용:  80509750.0
- 배추 가격:  [-4194.0864]
# 91000  손실 비용:  80509740.0
- 배추 가격:  [-4194.1025]
# 91500  손실 비용:  80509704.0
- 배추 가격:  [-

# 163000  손실 비용:  80506200.0
- 배추 가격:  [-4196.4077]
# 163500  손실 비용:  80506180.0
- 배추 가격:  [-4196.4233]
# 164000  손실 비용:  80506140.0
- 배추 가격:  [-4196.4395]
# 164500  손실 비용:  80506130.0
- 배추 가격:  [-4196.456]
# 165000  손실 비용:  80506104.0
- 배추 가격:  [-4196.471]
# 165500  손실 비용:  80506090.0
- 배추 가격:  [-4196.489]
# 166000  손실 비용:  80506056.0
- 배추 가격:  [-4196.5044]
# 166500  손실 비용:  80506030.0
- 배추 가격:  [-4196.519]
# 167000  손실 비용:  80506010.0
- 배추 가격:  [-4196.5356]
# 167500  손실 비용:  80505976.0
- 배추 가격:  [-4196.5513]
# 168000  손실 비용:  80505960.0
- 배추 가격:  [-4196.567]
# 168500  손실 비용:  80505940.0
- 배추 가격:  [-4196.582]
# 169000  손실 비용:  80505920.0
- 배추 가격:  [-4196.5977]
# 169500  손실 비용:  80505890.0
- 배추 가격:  [-4196.6143]
# 170000  손실 비용:  80505864.0
- 배추 가격:  [-4196.629]
# 170500  손실 비용:  80505840.0
- 배추 가격:  [-4196.6455]
# 171000  손실 비용:  80505820.0
- 배추 가격:  [-4196.6616]
# 171500  손실 비용:  80505784.0
- 배추 가격:  [-4196.6763]
# 172000  손실 비용:  80505770.0
- 배추 가격:  [-4196.6914]
# 172500  손실 비용:  8

# 243000  손실 비용:  80502424.0
- 배추 가격:  [-4198.925]
# 243500  손실 비용:  80502380.0
- 배추 가격:  [-4198.9404]
# 244000  손실 비용:  80502370.0
- 배추 가격:  [-4198.956]
# 244500  손실 비용:  80502344.0
- 배추 가격:  [-4198.97]
# 245000  손실 비용:  80502330.0
- 배추 가격:  [-4198.987]
# 245500  손실 비용:  80502290.0
- 배추 가격:  [-4199.003]
# 246000  손실 비용:  80502270.0
- 배추 가격:  [-4199.0176]
# 246500  손실 비용:  80502250.0
- 배추 가격:  [-4199.033]
# 247000  손실 비용:  80502240.0
- 배추 가격:  [-4199.049]
# 247500  손실 비용:  80502200.0
- 배추 가격:  [-4199.064]
# 248000  손실 비용:  80502184.0
- 배추 가격:  [-4199.079]
# 248500  손실 비용:  80502160.0
- 배추 가격:  [-4199.0947]
# 249000  손실 비용:  80502136.0
- 배추 가격:  [-4199.1104]
# 249500  손실 비용:  80502110.0
- 배추 가격:  [-4199.1265]
# 250000  손실 비용:  80502100.0
- 배추 가격:  [-4199.142]
# 250500  손실 비용:  80502070.0
- 배추 가격:  [-4199.1577]
# 251000  손실 비용:  80502040.0
- 배추 가격:  [-4199.174]
# 251500  손실 비용:  80502020.0
- 배추 가격:  [-4199.188]
# 252000  손실 비용:  80502000.0
- 배추 가격:  [-4199.2046]
# 252500  손실 비용:  8050197

# 323000  손실 비용:  80498780.0
- 배추 가격:  [-4201.38]
# 323500  손실 비용:  80498770.0
- 배추 가격:  [-4201.395]
# 324000  손실 비용:  80498740.0
- 배추 가격:  [-4201.411]
# 324500  손실 비용:  80498710.0
- 배추 가격:  [-4201.426]
# 325000  손실 비용:  80498696.0
- 배추 가격:  [-4201.4404]
# 325500  손실 비용:  80498680.0
- 배추 가격:  [-4201.457]
# 326000  손실 비용:  80498640.0
- 배추 가격:  [-4201.4717]
# 326500  손실 비용:  80498620.0
- 배추 가격:  [-4201.4873]
# 327000  손실 비용:  80498600.0
- 배추 가격:  [-4201.503]
# 327500  손실 비용:  80498590.0
- 배추 가격:  [-4201.5176]
# 328000  손실 비용:  80498550.0
- 배추 가격:  [-4201.5337]
# 328500  손실 비용:  80498536.0
- 배추 가격:  [-4201.549]
# 329000  손실 비용:  80498520.0
- 배추 가격:  [-4201.5645]
# 329500  손실 비용:  80498504.0
- 배추 가격:  [-4201.579]
# 330000  손실 비용:  80498480.0
- 배추 가격:  [-4201.594]
# 330500  손실 비용:  80498450.0
- 배추 가격:  [-4201.6094]
# 331000  손실 비용:  80498424.0
- 배추 가격:  [-4201.6235]
# 331500  손실 비용:  80498410.0
- 배추 가격:  [-4201.64]
# 332000  손실 비용:  80498380.0
- 배추 가격:  [-4201.6553]
# 332500  손실 비용:  804983

# 403000  손실 비용:  80495240.0
- 배추 가격:  [-4203.8286]
# 403500  손실 비용:  80495210.0
- 배추 가격:  [-4203.843]
# 404000  손실 비용:  80495180.0
- 배추 가격:  [-4203.8574]
# 404500  손실 비용:  80495170.0
- 배추 가격:  [-4203.8735]
# 405000  손실 비용:  80495140.0
- 배추 가격:  [-4203.8857]
# 405500  손실 비용:  80495120.0
- 배추 가격:  [-4203.903]
# 406000  손실 비용:  80495100.0
- 배추 가격:  [-4203.918]
# 406500  손실 비용:  80495080.0
- 배추 가격:  [-4203.932]
# 407000  손실 비용:  80495050.0
- 배추 가격:  [-4203.946]
# 407500  손실 비용:  80495040.0
- 배추 가격:  [-4203.962]
# 408000  손실 비용:  80495016.0
- 배추 가격:  [-4203.975]
# 408500  손실 비용:  80495000.0
- 배추 가격:  [-4203.9907]
# 409000  손실 비용:  80494984.0
- 배추 가격:  [-4204.006]
# 409500  손실 비용:  80494950.0
- 배추 가격:  [-4204.0215]
# 410000  손실 비용:  80494930.0
- 배추 가격:  [-4204.0356]
# 410500  손실 비용:  80494910.0
- 배추 가격:  [-4204.049]
# 411000  손실 비용:  80494900.0
- 배추 가격:  [-4204.0645]
# 411500  손실 비용:  80494860.0
- 배추 가격:  [-4204.0806]
# 412000  손실 비용:  80494850.0
- 배추 가격:  [-4204.094]
# 412500  손실 비용:  8049

# 483000  손실 비용:  80491850.0
- 배추 가격:  [-4206.1963]
# 483500  손실 비용:  80491830.0
- 배추 가격:  [-4206.212]
# 484000  손실 비용:  80491810.0
- 배추 가격:  [-4206.227]
# 484500  손실 비용:  80491784.0
- 배추 가격:  [-4206.241]
# 485000  손실 비용:  80491770.0
- 배추 가격:  [-4206.256]
# 485500  손실 비용:  80491750.0
- 배추 가격:  [-4206.27]
# 486000  손실 비용:  80491720.0
- 배추 가격:  [-4206.2856]
# 486500  손실 비용:  80491704.0
- 배추 가격:  [-4206.3003]
# 487000  손실 비용:  80491690.0
- 배추 가격:  [-4206.3145]
# 487500  손실 비용:  80491656.0
- 배추 가격:  [-4206.3296]
# 488000  손실 비용:  80491640.0
- 배추 가격:  [-4206.345]
# 488500  손실 비용:  80491624.0
- 배추 가격:  [-4206.36]
# 489000  손실 비용:  80491600.0
- 배추 가격:  [-4206.375]
# 489500  손실 비용:  80491580.0
- 배추 가격:  [-4206.3896]
# 490000  손실 비용:  80491550.0
- 배추 가격:  [-4206.404]
# 490500  손실 비용:  80491540.0
- 배추 가격:  [-4206.4185]
# 491000  손실 비용:  80491520.0
- 배추 가격:  [-4206.433]
# 491500  손실 비용:  80491496.0
- 배추 가격:  [-4206.4487]
# 492000  손실 비용:  80491470.0
- 배추 가격:  [-4206.463]
# 492500  손실 비용:  8049145

# 563000  손실 비용:  80488536.0
- 배추 가격:  [-4208.566]
# 563500  손실 비용:  80488510.0
- 배추 가격:  [-4208.5806]
# 564000  손실 비용:  80488480.0
- 배추 가격:  [-4208.5947]
# 564500  손실 비용:  80488460.0
- 배추 가격:  [-4208.61]
# 565000  손실 비용:  80488456.0
- 배추 가격:  [-4208.625]
# 565500  손실 비용:  80488430.0
- 배추 가격:  [-4208.6396]
# 566000  손실 비용:  80488420.0
- 배추 가격:  [-4208.654]
# 566500  손실 비용:  80488380.0
- 배추 가격:  [-4208.669]
# 567000  손실 비용:  80488360.0
- 배추 가격:  [-4208.684]
# 567500  손실 비용:  80488350.0
- 배추 가격:  [-4208.698]
# 568000  손실 비용:  80488340.0
- 배추 가격:  [-4208.7134]
# 568500  손실 비용:  80488296.0
- 배추 가격:  [-4208.729]
# 569000  손실 비용:  80488280.0
- 배추 가격:  [-4208.7437]
# 569500  손실 비용:  80488264.0
- 배추 가격:  [-4208.7583]
# 570000  손실 비용:  80488250.0
- 배추 가격:  [-4208.773]
# 570500  손실 비용:  80488216.0
- 배추 가격:  [-4208.787]
# 571000  손실 비용:  80488210.0
- 배추 가격:  [-4208.8027]
# 571500  손실 비용:  80488180.0
- 배추 가격:  [-4208.8164]
# 572000  손실 비용:  80488160.0
- 배추 가격:  [-4208.832]
# 572500  손실 비용:  804881

# 643000  손실 비용:  80485304.0
- 배추 가격:  [-4210.9077]
# 643500  손실 비용:  80485290.0
- 배추 가격:  [-4210.922]
# 644000  손실 비용:  80485260.0
- 배추 가격:  [-4210.9346]
# 644500  손실 비용:  80485240.0
- 배추 가격:  [-4210.949]
# 645000  손실 비용:  80485230.0
- 배추 가격:  [-4210.962]
# 645500  손실 비용:  80485210.0
- 배추 가격:  [-4210.9756]
# 646000  손실 비용:  80485200.0
- 배추 가격:  [-4210.99]
# 646500  손실 비용:  80485176.0
- 배추 가격:  [-4211.0044]
# 647000  손실 비용:  80485150.0
- 배추 가격:  [-4211.0186]
# 647500  손실 비용:  80485140.0
- 배추 가격:  [-4211.0317]
# 648000  손실 비용:  80485130.0
- 배추 가격:  [-4211.046]
# 648500  손실 비용:  80485096.0
- 배추 가격:  [-4211.0586]
# 649000  손실 비용:  80485070.0
- 배추 가격:  [-4211.073]
# 649500  손실 비용:  80485060.0
- 배추 가격:  [-4211.087]
# 650000  손실 비용:  80485040.0
- 배추 가격:  [-4211.101]
# 650500  손실 비용:  80485020.0
- 배추 가격:  [-4211.1157]
# 651000  손실 비용:  80485000.0
- 배추 가격:  [-4211.129]
# 651500  손실 비용:  80484984.0
- 배추 가격:  [-4211.1426]
# 652000  손실 비용:  80484980.0
- 배추 가격:  [-4211.156]
# 652500  손실 비용:  80484

# 723000  손실 비용:  80482300.0
- 배추 가격:  [-4213.1187]
# 723500  손실 비용:  80482296.0
- 배추 가격:  [-4213.132]
# 724000  손실 비용:  80482280.0
- 배추 가격:  [-4213.146]
# 724500  손실 비용:  80482260.0
- 배추 가격:  [-4213.1597]
# 725000  손실 비용:  80482240.0
- 배추 가격:  [-4213.1743]
# 725500  손실 비용:  80482220.0
- 배추 가격:  [-4213.1865]
# 726000  손실 비용:  80482216.0
- 배추 가격:  [-4213.201]
# 726500  손실 비용:  80482190.0
- 배추 가격:  [-4213.2144]
# 727000  손실 비용:  80482170.0
- 배추 가격:  [-4213.2295]
# 727500  손실 비용:  80482150.0
- 배추 가격:  [-4213.243]
# 728000  손실 비용:  80482130.0
- 배추 가격:  [-4213.256]
# 728500  손실 비용:  80482110.0
- 배추 가격:  [-4213.27]
# 729000  손실 비용:  80482100.0
- 배추 가격:  [-4213.2847]
# 729500  손실 비용:  80482070.0
- 배추 가격:  [-4213.2983]
# 730000  손실 비용:  80482060.0
- 배추 가격:  [-4213.3115]
# 730500  손실 비용:  80482040.0
- 배추 가격:  [-4213.325]
# 731000  손실 비용:  80482024.0
- 배추 가격:  [-4213.339]
# 731500  손실 비용:  80482000.0
- 배추 가격:  [-4213.3535]
# 732000  손실 비용:  80481980.0
- 배추 가격:  [-4213.367]
# 732500  손실 비용:  8048

# 803000  손실 비용:  80479384.0
- 배추 가격:  [-4215.329]
# 803500  손실 비용:  80479370.0
- 배추 가격:  [-4215.3423]
# 804000  손실 비용:  80479336.0
- 배추 가격:  [-4215.356]
# 804500  손실 비용:  80479320.0
- 배추 가격:  [-4215.3706]
# 805000  손실 비용:  80479304.0
- 배추 가격:  [-4215.385]
# 805500  손실 비용:  80479290.0
- 배추 가격:  [-4215.398]
# 806000  손실 비용:  80479260.0
- 배추 가격:  [-4215.4116]
# 806500  손실 비용:  80479250.0
- 배추 가격:  [-4215.426]
# 807000  손실 비용:  80479230.0
- 배추 가격:  [-4215.439]
# 807500  손실 비용:  80479220.0
- 배추 가격:  [-4215.454]
# 808000  손실 비용:  80479200.0
- 배추 가격:  [-4215.4673]
# 808500  손실 비용:  80479176.0
- 배추 가격:  [-4215.481]
# 809000  손실 비용:  80479160.0
- 배추 가격:  [-4215.495]
# 809500  손실 비용:  80479150.0
- 배추 가격:  [-4215.509]
# 810000  손실 비용:  80479120.0
- 배추 가격:  [-4215.5225]
# 810500  손실 비용:  80479110.0
- 배추 가격:  [-4215.5366]
# 811000  손실 비용:  80479080.0
- 배추 가격:  [-4215.5503]
# 811500  손실 비용:  80479064.0
- 배추 가격:  [-4215.564]
# 812000  손실 비용:  80479050.0
- 배추 가격:  [-4215.577]
# 812500  손실 비용:  804790

# 883000  손실 비용:  80476490.0
- 배추 가격:  [-4217.5405]
# 883500  손실 비용:  80476470.0
- 배추 가격:  [-4217.553]
# 884000  손실 비용:  80476450.0
- 배추 가격:  [-4217.5684]
# 884500  손실 비용:  80476430.0
- 배추 가격:  [-4217.5806]
# 885000  손실 비용:  80476420.0
- 배추 가격:  [-4217.5947]
# 885500  손실 비용:  80476400.0
- 배추 가격:  [-4217.609]
# 886000  손실 비용:  80476380.0
- 배추 가격:  [-4217.623]
# 886500  손실 비용:  80476370.0
- 배추 가격:  [-4217.6367]
# 887000  손실 비용:  80476350.0
- 배추 가격:  [-4217.651]
# 887500  손실 비용:  80476340.0
- 배추 가격:  [-4217.665]
# 888000  손실 비용:  80476320.0
- 배추 가격:  [-4217.678]
# 888500  손실 비용:  80476296.0
- 배추 가격:  [-4217.692]
# 889000  손실 비용:  80476270.0
- 배추 가격:  [-4217.706]
# 889500  손실 비용:  80476260.0
- 배추 가격:  [-4217.7197]
# 890000  손실 비용:  80476240.0
- 배추 가격:  [-4217.7334]
# 890500  손실 비용:  80476220.0
- 배추 가격:  [-4217.7466]
# 891000  손실 비용:  80476210.0
- 배추 가격:  [-4217.7607]
# 891500  손실 비용:  80476184.0
- 배추 가격:  [-4217.775]
# 892000  손실 비용:  80476170.0
- 배추 가격:  [-4217.789]
# 892500  손실 비용:  8047

# 963000  손실 비용:  80473680.0
- 배추 가격:  [-4219.729]
# 963500  손실 비용:  80473660.0
- 배추 가격:  [-4219.742]
# 964000  손실 비용:  80473656.0
- 배추 가격:  [-4219.755]
# 964500  손실 비용:  80473650.0
- 배추 가격:  [-4219.768]
# 965000  손실 비용:  80473620.0
- 배추 가격:  [-4219.781]
# 965500  손실 비용:  80473590.0
- 배추 가격:  [-4219.7935]
# 966000  손실 비용:  80473580.0
- 배추 가격:  [-4219.8066]
# 966500  손실 비용:  80473576.0
- 배추 가격:  [-4219.8184]
# 967000  손실 비용:  80473544.0
- 배추 가격:  [-4219.831]
# 967500  손실 비용:  80473540.0
- 배추 가격:  [-4219.8447]
# 968000  손실 비용:  80473520.0
- 배추 가격:  [-4219.8574]
# 968500  손실 비용:  80473500.0
- 배추 가격:  [-4219.8706]
# 969000  손실 비용:  80473496.0
- 배추 가격:  [-4219.883]
# 969500  손실 비용:  80473464.0
- 배추 가격:  [-4219.8965]
# 970000  손실 비용:  80473460.0
- 배추 가격:  [-4219.9097]
# 970500  손실 비용:  80473440.0
- 배추 가격:  [-4219.922]
# 971000  손실 비용:  80473420.0
- 배추 가격:  [-4219.935]
# 971500  손실 비용:  80473410.0
- 배추 가격:  [-4219.947]
# 972000  손실 비용:  80473390.0
- 배추 가격:  [-4219.9595]
# 972500  손실 비용:  8047

In [23]:
saver = tf.train.Saver()
#학습모델 이용에 있어서 최적화 등의 요소는 고려하지 않고 단순하게 세이버를 이용해서 학습된 모델을 추출하는방법
save_path = saver.save(sess,"./test1/test.saved.cpkt")

ValueError: At least two variables have the same name: bias

In [5]:
#저장된것을 가져오기 위한 객체 초기화
saver = tf.train.Saver()
model= tf.global_variables_initializer()

ValueError: No variables to save

In [5]:
#테스트 실험
X = tf.placeholder(tf.float32, shape=[None,10]) #4개의 변인이 담길수 있게
Y = tf.placeholder(tf.float32, shape=[None,1]) 
W = tf.Variable(tf.random_normal([10,1]), name="weight") #가중치
b = tf.Variable(tf.random_normal([1]), name="bias") #bias 값

hypothesis = tf.matmul(X,W, name="operation") +b 

#저장된것을 가져오기 위한 객체 초기화
saver = tf.train.Saver()
model= tf.global_variables_initializer()

In [5]:
#https://jangjy.tistory.com/297

new_saver = tf.train.Saver()
with tf.Session() as sess:
    new_saver = tf.train.import_meta_graph("./save/test.saved.cpkt.meta")
    new_saver.restore(sess.tf.train.latest_checkpoint("./save/test.saved.cpkt"))
 
    g = tf.get_default_graph()
    
    g_collection_key_list = g.get_all_collection_keys()
 
    g_collection_list = g.get_collection(g_collection_key_list[0])
 
    oper_list = g.get_operations()
    
    # 기존 그래프를 import, 새로운 데이터를입력으로 사용하여 연산
    new_v0 = g.get_tensor_by_name("v0:0")
    #feed_dict = {new_v0:9}
    
    for step in range(15000001):
        cost_, hypo_, _ = sess.run([cost,hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step % 500 == 0:
            print("#", step, " 손실 비용: ", cost_)
            print("- 배추 가격: ",hypo_[0])#예측되고 있는 배추 가격 #첫번째 데이터에 대해서
    
    #output = sess.run(["v3:0"], feed_dict={X: x_data, Y: y_data})
    #print(output)
    
    '''

    # 기존 그래프에 새로운 그래프를 연결하여 연산
    new_v3 = g.get_tensor_by_name("v3:0")
    add_on_op = tf.multiply(new_v3, 3, name="multiply")
    print(sess.run(add_on_op, feed_dict))
    '''

ValueError: No variables to save

In [6]:
sess=tf.Session()  
saver = tf.train.import_meta_graph('./test/test_saved.cpkt.meta')
saver.restore(sess, './test/test_saved.cpkt')   

#saver.restore(sess,tf.train.latest_checkpoint('./test/test_saved.cpkt'))

graph = tf.get_default_graph()
# default graph로 초기화 해주는 것이 안전하다.


for op in tf.get_default_graph().get_operations():
    print(op.name)



#W1 = graph.get_tensor_by_name('cham:0')
X1 = graph.get_tensor_by_name('cham:0')
Y1 = graph.get_tensor_by_name('gold:0')
B1 = graph.get_tensor_by_name('bias:0')



#tf.matmul(X, W) + b
hypothesis = graph.get_tensor_by_name('operation:0')+B1

cost1 = graph.get_tensor_by_name('result:0')



optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.000005) #학습률 정도(매우 중요)
train = optimizer.minimize(cost1) #훈련 설정


for step in range(1000001):
    cost_, hypo_, _ = sess.run([cost1,hypothesis, train], feed_dict={X1: x_data, Y1: y_data})
    if step % 500 == 0:
        print("#", step, " 손실 비용: ", cost_)
        print("- 배추 가격: ",hypo_[0])#예측되고 있는 배추 가격 #첫번째 데이터에 대해서


#hypo_= sess.run(hypothesis, feed_dict={W1:x_data ,Y1:y_data})
#print("- 배추 가격: ",hypo_[0])#예측되고 있는 배추 가격 #첫번째 데이터에 대해서





#co = graph.get_tensor_by_name('result:0')


'''
for step in range(15000001):
    hypo_= sess.run(hypothesis, feed_dict={W1:x_data ,Y1:y_data})
    if step % 500 == 0:
        print("#", step, " 손실 비용: ")
        print("- 배추 가격: ",hypo_[0])#예측되고 있는 배추 가격 #첫번째 데이터에 대해서

'''










INFO:tensorflow:Restoring parameters from ./test/test_saved.cpkt
cham
gold
random_normal/shape
random_normal/mean
random_normal/stddev
random_normal/RandomStandardNormal
random_normal/mul
random_normal
weight
weight/Assign
weight/read
random_normal_1/shape
random_normal_1/mean
random_normal_1/stddev
random_normal_1/RandomStandardNormal
random_normal_1/mul
random_normal_1
bias
bias/Assign
bias/read
operation
add
sub
Square
Const
result
gradients/Shape
gradients/grad_ys_0
gradients/Fill
gradients/result_grad/Reshape/shape
gradients/result_grad/Reshape
gradients/result_grad/Shape
gradients/result_grad/Tile
gradients/result_grad/Shape_1
gradients/result_grad/Shape_2
gradients/result_grad/Const
gradients/result_grad/Prod
gradients/result_grad/Const_1
gradients/result_grad/Prod_1
gradients/result_grad/Maximum/y
gradients/result_grad/Maximum
gradients/result_grad/floordiv
gradients/result_grad/Cast
gradients/result_grad/truediv
gradients/Square_grad/Const
gradients/Square_grad/Mul
gradients/S

# 20500  손실 비용:  80471176.0
- 배추 가격:  [-4221.7217]
# 21000  손실 비용:  80471140.0
- 배추 가격:  [-4221.748]
# 21500  손실 비용:  80471110.0
- 배추 가격:  [-4221.7734]
# 22000  손실 비용:  80471070.0
- 배추 가격:  [-4221.799]
# 22500  손실 비용:  80471050.0
- 배추 가격:  [-4221.824]
# 23000  손실 비용:  80471016.0
- 배추 가격:  [-4221.8496]
# 23500  손실 비용:  80470980.0
- 배추 가격:  [-4221.874]
# 24000  손실 비용:  80470940.0
- 배추 가격:  [-4221.9]
# 24500  손실 비용:  80470920.0
- 배추 가격:  [-4221.9253]
# 25000  손실 비용:  80470890.0
- 배추 가격:  [-4221.95]
# 25500  손실 비용:  80470856.0
- 배추 가격:  [-4221.9756]
# 26000  손실 비용:  80470820.0
- 배추 가격:  [-4222.0015]
# 26500  손실 비용:  80470790.0
- 배추 가격:  [-4222.0273]
# 27000  손실 비용:  80470770.0
- 배추 가격:  [-4222.0527]
# 27500  손실 비용:  80470730.0
- 배추 가격:  [-4222.0776]
# 28000  손실 비용:  80470696.0
- 배추 가격:  [-4222.104]
# 28500  손실 비용:  80470670.0
- 배추 가격:  [-4222.1294]
# 29000  손실 비용:  80470630.0
- 배추 가격:  [-4222.156]
# 29500  손실 비용:  80470610.0
- 배추 가격:  [-4222.18]
# 30000  손실 비용:  80470580.0
- 배추 가격:  [-4222

# 102500  손실 비용:  80466200.0
- 배추 가격:  [-4225.769]
# 103000  손실 비용:  80466170.0
- 배추 가격:  [-4225.792]
# 103500  손실 비용:  80466150.0
- 배추 가격:  [-4225.8164]
# 104000  손실 비용:  80466110.0
- 배추 가격:  [-4225.8394]
# 104500  손실 비용:  80466090.0
- 배추 가격:  [-4225.861]
# 105000  손실 비용:  80466056.0
- 배추 가격:  [-4225.887]
# 105500  손실 비용:  80466024.0
- 배추 가격:  [-4225.909]
# 106000  손실 비용:  80466000.0
- 배추 가격:  [-4225.9346]
# 106500  손실 비용:  80465970.0
- 배추 가격:  [-4225.9565]
# 107000  손실 비용:  80465944.0
- 배추 가격:  [-4225.981]
# 107500  손실 비용:  80465920.0
- 배추 가격:  [-4226.005]
# 108000  손실 비용:  80465890.0
- 배추 가격:  [-4226.028]
# 108500  손실 비용:  80465850.0
- 배추 가격:  [-4226.0513]
# 109000  손실 비용:  80465820.0
- 배추 가격:  [-4226.075]
# 109500  손실 비용:  80465810.0
- 배추 가격:  [-4226.099]
# 110000  손실 비용:  80465780.0
- 배추 가격:  [-4226.122]
# 110500  손실 비용:  80465750.0
- 배추 가격:  [-4226.145]
# 111000  손실 비용:  80465720.0
- 배추 가격:  [-4226.1694]
# 111500  손실 비용:  80465690.0
- 배추 가격:  [-4226.193]
# 112000  손실 비용:  8046566

# 183000  손실 비용:  80461710.0
- 배추 가격:  [-4229.552]
# 183500  손실 비용:  80461680.0
- 배추 가격:  [-4229.5747]
# 184000  손실 비용:  80461656.0
- 배추 가격:  [-4229.5996]
# 184500  손실 비용:  80461630.0
- 배추 가격:  [-4229.6216]
# 185000  손실 비용:  80461590.0
- 배추 가격:  [-4229.646]
# 185500  손실 비용:  80461570.0
- 배추 가격:  [-4229.6685]
# 186000  손실 비용:  80461550.0
- 배추 가격:  [-4229.692]
# 186500  손실 비용:  80461520.0
- 배추 가격:  [-4229.7163]
# 187000  손실 비용:  80461496.0
- 배추 가격:  [-4229.7373]
# 187500  손실 비용:  80461464.0
- 배추 가격:  [-4229.761]
# 188000  손실 비용:  80461420.0
- 배추 가격:  [-4229.7866]
# 188500  손실 비용:  80461410.0
- 배추 가격:  [-4229.81]
# 189000  손실 비용:  80461384.0
- 배추 가격:  [-4229.833]
# 189500  손실 비용:  80461360.0
- 배추 가격:  [-4229.858]
# 190000  손실 비용:  80461330.0
- 배추 가격:  [-4229.881]
# 190500  손실 비용:  80461300.0
- 배추 가격:  [-4229.9023]
# 191000  손실 비용:  80461260.0
- 배추 가격:  [-4229.9253]
# 191500  손실 비용:  80461240.0
- 배추 가격:  [-4229.9497]
# 192000  손실 비용:  80461220.0
- 배추 가격:  [-4229.9746]
# 192500  손실 비용:  804

# 263000  손실 비용:  80457400.0
- 배추 가격:  [-4233.312]
# 263500  손실 비용:  80457380.0
- 배추 가격:  [-4233.3354]
# 264000  손실 비용:  80457350.0
- 배추 가격:  [-4233.3584]
# 264500  손실 비용:  80457320.0
- 배추 가격:  [-4233.3804]
# 265000  손실 비용:  80457300.0
- 배추 가격:  [-4233.4033]
# 265500  손실 비용:  80457260.0
- 배추 가격:  [-4233.4272]
# 266000  손실 비용:  80457230.0
- 배추 가격:  [-4233.4526]
# 266500  손실 비용:  80457210.0
- 배추 가격:  [-4233.477]
# 267000  손실 비용:  80457180.0
- 배추 가격:  [-4233.499]
# 267500  손실 비용:  80457150.0
- 배추 가격:  [-4233.523]
# 268000  손실 비용:  80457130.0
- 배추 가격:  [-4233.546]
# 268500  손실 비용:  80457110.0
- 배추 가격:  [-4233.5713]
# 269000  손실 비용:  80457070.0
- 배추 가격:  [-4233.593]
# 269500  손실 비용:  80457050.0
- 배추 가격:  [-4233.616]
# 270000  손실 비용:  80457020.0
- 배추 가격:  [-4233.64]
# 270500  손실 비용:  80456990.0
- 배추 가격:  [-4233.664]
# 271000  손실 비용:  80456980.0
- 배추 가격:  [-4233.687]
# 271500  손실 비용:  80456940.0
- 배추 가격:  [-4233.711]
# 272000  손실 비용:  80456910.0
- 배추 가격:  [-4233.735]
# 272500  손실 비용:  8045689

# 343000  손실 비용:  80453224.0
- 배추 가격:  [-4237.074]
# 343500  손실 비용:  80453200.0
- 배추 가격:  [-4237.0977]
# 344000  손실 비용:  80453176.0
- 배추 가격:  [-4237.1196]
# 344500  손실 비용:  80453150.0
- 배추 가격:  [-4237.144]
# 345000  손실 비용:  80453130.0
- 배추 가격:  [-4237.168]
# 345500  손실 비용:  80453100.0
- 배추 가격:  [-4237.1914]
# 346000  손실 비용:  80453064.0
- 배추 가격:  [-4237.215]
# 346500  손실 비용:  80453050.0
- 배추 가격:  [-4237.2393]
# 347000  손실 비용:  80453016.0
- 배추 가격:  [-4237.2607]
# 347500  손실 비용:  80453010.0
- 배추 가격:  [-4237.2827]
# 348000  손실 비용:  80452980.0
- 배추 가격:  [-4237.308]
# 348500  손실 비용:  80452950.0
- 배추 가격:  [-4237.3315]
# 349000  손실 비용:  80452920.0
- 배추 가격:  [-4237.356]
# 349500  손실 비용:  80452910.0
- 배추 가격:  [-4237.3774]
# 350000  손실 비용:  80452870.0
- 배추 가격:  [-4237.4]
# 350500  손실 비용:  80452850.0
- 배추 가격:  [-4237.425]
# 351000  손실 비용:  80452820.0
- 배추 가격:  [-4237.4473]
# 351500  손실 비용:  80452790.0
- 배추 가격:  [-4237.4717]
# 352000  손실 비용:  80452770.0
- 배추 가격:  [-4237.4956]
# 352500  손실 비용:  8045

# 423500  손실 비용:  80449190.0
- 배추 가격:  [-4240.8555]
# 424000  손실 비용:  80449170.0
- 배추 가격:  [-4240.879]
# 424500  손실 비용:  80449140.0
- 배추 가격:  [-4240.9023]
# 425000  손실 비용:  80449120.0
- 배추 가격:  [-4240.9243]
# 425500  손실 비용:  80449096.0
- 배추 가격:  [-4240.951]
# 426000  손실 비용:  80449080.0
- 배추 가격:  [-4240.9727]
# 426500  손실 비용:  80449050.0
- 배추 가격:  [-4240.9956]
# 427000  손실 비용:  80449016.0
- 배추 가격:  [-4241.0195]
# 427500  손실 비용:  80449000.0
- 배추 가격:  [-4241.042]
# 428000  손실 비용:  80448970.0
- 배추 가격:  [-4241.066]
# 428500  손실 비용:  80448950.0
- 배추 가격:  [-4241.0913]
# 429000  손실 비용:  80448920.0
- 배추 가격:  [-4241.114]
# 429500  손실 비용:  80448904.0
- 배추 가격:  [-4241.1377]
# 430000  손실 비용:  80448860.0
- 배추 가격:  [-4241.159]
# 430500  손실 비용:  80448850.0
- 배추 가격:  [-4241.184]
# 431000  손실 비용:  80448820.0
- 배추 가격:  [-4241.208]
# 431500  손실 비용:  80448800.0
- 배추 가격:  [-4241.232]
# 432000  손실 비용:  80448776.0
- 배추 가격:  [-4241.2554]
# 432500  손실 비용:  80448744.0
- 배추 가격:  [-4241.278]
# 433000  손실 비용:  8044

# 503500  손실 비용:  80445810.0
- 배추 가격:  [-4244.1416]
# 504000  손실 비용:  80445790.0
- 배추 가격:  [-4244.1616]
# 504500  손실 비용:  80445770.0
- 배추 가격:  [-4244.1807]
# 505000  손실 비용:  80445750.0
- 배추 가격:  [-4244.2]
# 505500  손실 비용:  80445720.0
- 배추 가격:  [-4244.2197]
# 506000  손실 비용:  80445704.0
- 배추 가격:  [-4244.2397]
# 506500  손실 비용:  80445690.0
- 배추 가격:  [-4244.259]
# 507000  손실 비용:  80445660.0
- 배추 가격:  [-4244.279]
# 507500  손실 비용:  80445650.0
- 배추 가격:  [-4244.297]
# 508000  손실 비용:  80445624.0
- 배추 가격:  [-4244.3184]
# 508500  손실 비용:  80445610.0
- 배추 가격:  [-4244.338]
# 509000  손실 비용:  80445590.0
- 배추 가격:  [-4244.3574]
# 509500  손실 비용:  80445576.0
- 배추 가격:  [-4244.377]
# 510000  손실 비용:  80445544.0
- 배추 가격:  [-4244.3965]
# 510500  손실 비용:  80445540.0
- 배추 가격:  [-4244.4155]
# 511000  손실 비용:  80445500.0
- 배추 가격:  [-4244.436]
# 511500  손실 비용:  80445496.0
- 배추 가격:  [-4244.4556]
# 512000  손실 비용:  80445464.0
- 배추 가격:  [-4244.4746]
# 512500  손실 비용:  80445450.0
- 배추 가격:  [-4244.4956]
# 513000  손실 비용:  804

# 583500  손실 비용:  80442690.0
- 배추 가격:  [-4247.2734]
# 584000  손실 비용:  80442670.0
- 배추 가격:  [-4247.293]
# 584500  손실 비용:  80442650.0
- 배추 가격:  [-4247.3125]
# 585000  손실 비용:  80442620.0
- 배추 가격:  [-4247.332]
# 585500  손실 비용:  80442610.0
- 배추 가격:  [-4247.3516]
# 586000  손실 비용:  80442590.0
- 배추 가격:  [-4247.3716]
# 586500  손실 비용:  80442560.0
- 배추 가격:  [-4247.388]
# 587000  손실 비용:  80442540.0
- 배추 가격:  [-4247.4106]
# 587500  손실 비용:  80442536.0
- 배추 가격:  [-4247.429]
# 588000  손실 비용:  80442510.0
- 배추 가격:  [-4247.4497]
# 588500  손실 비용:  80442504.0
- 배추 가격:  [-4247.468]
# 589000  손실 비용:  80442470.0
- 배추 가격:  [-4247.4873]
# 589500  손실 비용:  80442456.0
- 배추 가격:  [-4247.508]
# 590000  손실 비용:  80442440.0
- 배추 가격:  [-4247.526]
# 590500  손실 비용:  80442424.0
- 배추 가격:  [-4247.5464]
# 591000  손실 비용:  80442390.0
- 배추 가격:  [-4247.567]
# 591500  손실 비용:  80442376.0
- 배추 가격:  [-4247.5854]
# 592000  손실 비용:  80442360.0
- 배추 가격:  [-4247.604]
# 592500  손실 비용:  80442344.0
- 배추 가격:  [-4247.622]
# 593000  손실 비용:  8044

# 663500  손실 비용:  80439660.0
- 배추 가격:  [-4250.4023]
# 664000  손실 비용:  80439656.0
- 배추 가격:  [-4250.423]
# 664500  손실 비용:  80439630.0
- 배추 가격:  [-4250.4414]
# 665000  손실 비용:  80439620.0
- 배추 가격:  [-4250.4595]
# 665500  손실 비용:  80439600.0
- 배추 가격:  [-4250.4814]
# 666000  손실 비용:  80439576.0
- 배추 가격:  [-4250.5005]
# 666500  손실 비용:  80439560.0
- 배추 가격:  [-4250.519]
# 667000  손실 비용:  80439544.0
- 배추 가격:  [-4250.5396]
# 667500  손실 비용:  80439530.0
- 배추 가격:  [-4250.5596]
# 668000  손실 비용:  80439496.0
- 배추 가격:  [-4250.5786]
# 668500  손실 비용:  80439490.0
- 배추 가격:  [-4250.5986]
# 669000  손실 비용:  80439464.0
- 배추 가격:  [-4250.6177]
# 669500  손실 비용:  80439440.0
- 배추 가격:  [-4250.6377]
# 670000  손실 비용:  80439430.0
- 배추 가격:  [-4250.6562]
# 670500  손실 비용:  80439416.0
- 배추 가격:  [-4250.6753]
# 671000  손실 비용:  80439384.0
- 배추 가격:  [-4250.697]
# 671500  손실 비용:  80439380.0
- 배추 가격:  [-4250.716]
# 672000  손실 비용:  80439360.0
- 배추 가격:  [-4250.7363]
# 672500  손실 비용:  80439350.0
- 배추 가격:  [-4250.7554]
# 673000  손실 비용:

# 743500  손실 비용:  80436760.0
- 배추 가격:  [-4253.537]
# 744000  손실 비용:  80436740.0
- 배추 가격:  [-4253.556]
# 744500  손실 비용:  80436720.0
- 배추 가격:  [-4253.5757]
# 745000  손실 비용:  80436700.0
- 배추 가격:  [-4253.5957]
# 745500  손실 비용:  80436690.0
- 배추 가격:  [-4253.6133]
# 746000  손실 비용:  80436664.0
- 배추 가격:  [-4253.6343]
# 746500  손실 비용:  80436650.0
- 배추 가격:  [-4253.654]
# 747000  손실 비용:  80436630.0
- 배추 가격:  [-4253.6724]
# 747500  손실 비용:  80436616.0
- 배추 가격:  [-4253.694]
# 748000  손실 비용:  80436584.0
- 배추 가격:  [-4253.713]
# 748500  손실 비용:  80436580.0
- 배추 가격:  [-4253.732]
# 749000  손실 비용:  80436560.0
- 배추 가격:  [-4253.7515]
# 749500  손실 비용:  80436536.0
- 배추 가격:  [-4253.772]
# 750000  손실 비용:  80436510.0
- 배추 가격:  [-4253.791]
# 750500  손실 비용:  80436504.0
- 배추 가격:  [-4253.8105]
# 751000  손실 비용:  80436490.0
- 배추 가격:  [-4253.8296]
# 751500  손실 비용:  80436470.0
- 배추 가격:  [-4253.847]
# 752000  손실 비용:  80436456.0
- 배추 가격:  [-4253.87]
# 752500  손실 비용:  80436430.0
- 배추 가격:  [-4253.8887]
# 753000  손실 비용:  80436

# 823500  손실 비용:  80433950.0
- 배추 가격:  [-4256.6685]
# 824000  손실 비용:  80433940.0
- 배추 가격:  [-4256.687]
# 824500  손실 비용:  80433920.0
- 배추 가격:  [-4256.7075]
# 825000  손실 비용:  80433890.0
- 배추 가격:  [-4256.727]
# 825500  손실 비용:  80433870.0
- 배추 가격:  [-4256.746]
# 826000  손실 비용:  80433864.0
- 배추 가격:  [-4256.7646]
# 826500  손실 비용:  80433850.0
- 배추 가격:  [-4256.7847]
# 827000  손실 비용:  80433820.0
- 배추 가격:  [-4256.8057]
# 827500  손실 비용:  80433810.0
- 배추 가격:  [-4256.824]
# 828000  손실 비용:  80433784.0
- 배추 가격:  [-4256.8447]
# 828500  손실 비용:  80433780.0
- 배추 가격:  [-4256.8643]
# 829000  손실 비용:  80433750.0
- 배추 가격:  [-4256.884]
# 829500  손실 비용:  80433740.0
- 배추 가격:  [-4256.902]
# 830000  손실 비용:  80433730.0
- 배추 가격:  [-4256.921]
# 830500  손실 비용:  80433710.0
- 배추 가격:  [-4256.9424]
# 831000  손실 비용:  80433690.0
- 배추 가격:  [-4256.961]
# 831500  손실 비용:  80433660.0
- 배추 가격:  [-4256.9814]
# 832000  손실 비용:  80433656.0
- 배추 가격:  [-4257.0005]
# 832500  손실 비용:  80433640.0
- 배추 가격:  [-4257.0205]
# 833000  손실 비용:  80

# 903500  손실 비용:  80431650.0
- 배추 가격:  [-4259.3164]
# 904000  손실 비용:  80431640.0
- 배추 가격:  [-4259.333]
# 904500  손실 비용:  80431624.0
- 배추 가격:  [-4259.3477]
# 905000  손실 비용:  80431610.0
- 배추 가격:  [-4259.363]
# 905500  손실 비용:  80431600.0
- 배추 가격:  [-4259.3794]
# 906000  손실 비용:  80431580.0
- 배추 가격:  [-4259.395]
# 906500  손실 비용:  80431570.0
- 배추 가격:  [-4259.4116]
# 907000  손실 비용:  80431550.0
- 배추 가격:  [-4259.4263]
# 907500  손실 비용:  80431550.0
- 배추 가격:  [-4259.4424]
# 908000  손실 비용:  80431540.0
- 배추 가격:  [-4259.458]
# 908500  손실 비용:  80431510.0
- 배추 가격:  [-4259.473]
# 909000  손실 비용:  80431510.0
- 배추 가격:  [-4259.4897]
# 909500  손실 비용:  80431496.0
- 배추 가격:  [-4259.5054]
# 910000  손실 비용:  80431480.0
- 배추 가격:  [-4259.52]
# 910500  손실 비용:  80431464.0
- 배추 가격:  [-4259.536]
# 911000  손실 비용:  80431450.0
- 배추 가격:  [-4259.5522]
# 911500  손실 비용:  80431440.0
- 배추 가격:  [-4259.5674]
# 912000  손실 비용:  80431420.0
- 배추 가격:  [-4259.5825]
# 912500  손실 비용:  80431416.0
- 배추 가격:  [-4259.598]
# 913000  손실 비용:  804

# 983500  손실 비용:  80429550.0
- 배추 가격:  [-4261.8228]
# 984000  손실 비용:  80429540.0
- 배추 가격:  [-4261.838]
# 984500  손실 비용:  80429520.0
- 배추 가격:  [-4261.853]
# 985000  손실 비용:  80429500.0
- 배추 가격:  [-4261.869]
# 985500  손실 비용:  80429496.0
- 배추 가격:  [-4261.8853]
# 986000  손실 비용:  80429490.0
- 배추 가격:  [-4261.9004]
# 986500  손실 비용:  80429470.0
- 배추 가격:  [-4261.9165]
# 987000  손실 비용:  80429464.0
- 배추 가격:  [-4261.9316]
# 987500  손실 비용:  80429460.0
- 배추 가격:  [-4261.947]
# 988000  손실 비용:  80429430.0
- 배추 가격:  [-4261.963]
# 988500  손실 비용:  80429420.0
- 배추 가격:  [-4261.978]
# 989000  손실 비용:  80429400.0
- 배추 가격:  [-4261.9956]
# 989500  손실 비용:  80429390.0
- 배추 가격:  [-4262.01]
# 990000  손실 비용:  80429384.0
- 배추 가격:  [-4262.026]
# 990500  손실 비용:  80429370.0
- 배추 가격:  [-4262.0396]
# 991000  손실 비용:  80429360.0
- 배추 가격:  [-4262.0566]
# 991500  손실 비용:  80429340.0
- 배추 가격:  [-4262.073]
# 992000  손실 비용:  80429330.0
- 배추 가격:  [-4262.088]
# 992500  손실 비용:  80429310.0
- 배추 가격:  [-4262.104]
# 993000  손실 비용:  804293

'\nfor step in range(15000001):\n    hypo_= sess.run(hypothesis, feed_dict={W1:x_data ,Y1:y_data})\n    if step % 500 == 0:\n        print("#", step, " 손실 비용: ")\n        print("- 배추 가격: ",hypo_[0])#예측되고 있는 배추 가격 #첫번째 데이터에 대해서\n\n'

In [11]:
print(W1)
#print(D1)
print(x_data[0,1])

Tensor("cham:0", shape=(?, 10), dtype=float32)
82.0


In [11]:
#학습된 모델을 저장하는 방법
#- 배추 가격:  [1404.1737]
# 10975000  손실 비용:  91622480.0
#- 배추 가격:  [1404.1737]

#간단한 방법이라서 간단한 프로젝트를 만들때는 요긴하게 사용된다.
saver = tf.train.Saver()
#학습모델 이용에 있어서 최적화 등의 요소는 고려하지 않고 단순하게 세이버를 이용해서 학습된 모델을 추출하는방법
save_path = saver.save(sess,"./test/test_saved.cpkt")
print("학습된 모델을 저장했습니다.")

학습된 모델을 저장했습니다.


In [4]:
#테스트 실험
X = tf.placeholder(tf.float32, shape=[None,10]) #4개의 변인이 담길수 있게
Y = tf.placeholder(tf.float32, shape=[None,1]) 
W = tf.Variable(tf.random_normal([10,1]), name="weight") #가중치
b = tf.Variable(tf.random_normal([1]), name="bias") #bias 값

hypothesis = tf.matmul(X,W) +b 

#저장된것을 가져오기 위한 객체 초기화
saver = tf.train.Saver()
model= tf.global_variables_initializer()

#사용자로부터 10가지 변수를 입력 받음
top= float(input('top : '))
jg = float(input('jg : '))
mid = float(input('mid : '))
ad = float(input('ad : '))
sup = float(input('sup : '))

e_top= float(input('e_top: '))
e_jg = float(input('e_jg: '))
e_mid = float(input('e_mid: '))
e_ad = float(input('e_ad: '))
e_sup = float(input('e_sup: '))

with tf.Session() as sess:
    sess.run(model)
    
    save_path="./saved.cpkt"
    saver.restore(sess,save_path) #해당 세션에 저장된 학습 모델을 불러올수 있도록 함
    
    #기존에 학습된 데이터가 2차원 배열이기 때문에 맞추어 줘야 한다.
    data = ((top, jg, mid, ad, sup, e_top, e_jg, e_mid, e_ad, e_sup), )
    
    #사용자가 입력한 데이터를 토대로 행렬로 초기화를 해주고
    arr = np.array(data, dtype=np.float32)
    
    x_data = arr[0:10]
    #입력한 데이터를 X에 담아서 모델을 돌려보았다
    dict = sess.run(hypothesis, feed_dict={X: x_data})
    
    #데이터를 하나만 넣었기 때문에 출력은 하나만 하면 된다.
    print(dict[0])

top : 138
jg : 11
mid : 93
ad : 76
sup : 68
e_top: 20
e_jg: 28
e_mid: 116
e_ad: 55
e_sup: 134
INFO:tensorflow:Restoring parameters from ./saved.cpkt
[-18.96186]


In [26]:
print(x_data)

[[ 13.  82.  53.  40. 134.  45.  83. 114.  80.  77.]
 [ 75.   9.  73.  76.  39.  57. 135. 106.  95. 112.]
 [ 35.   4.   1.  57.  55.  84.  28.  53.  95.  92.]
 [ 13.  23. 138.  95. 134.  21.  82.  73. 120. 101.]
 [142.  23. 116.  25. 131.  84.  28.  20. 120.  68.]
 [ 35.  87.  27.  80.  39. 144. 113.  53. 146.  20.]
 [ 93.  84. 126. 120. 131.  25.  23.  82.  40.  46.]
 [  2. 100. 145.  38. 134.  57.  28.  53.  76.  68.]
 [ 75.  23. 116.  76. 131. 113.  28.   1. 120.   8.]
 [105.  72. 114. 120.  68.  50.  28.  86.  76.  77.]
 [ 35.  56. 129.  40.  68.  20.  84.  30.  38.  57.]
 [ 32.  97.   1.  76.  68. 105.  28. 106.  40.  92.]
 [ 21.  28. 138.   8.  55.  53.  97.  66.  40.  12.]
 [113.  28.  66.  38.   8.  35.  11.  25. 117.  22.]
 [ 20.  97.  48. 120. 131.  75.  28. 106.  95.  46.]
 [ 13.  87.  33.  76.  51. 144.  94. 106. 120. 131.]
 [127. 115. 105.  40. 101.   0.  23. 106. 117.  77.]
 [ 74. 135.  33. 120. 131.   7.  97.  55. 109. 134.]
 [ 13.  87. 106.  95.  55. 102.  28.  32. 120.

In [31]:
print(y_data)

[[-10795.]
 [ -7644.]
 [ 17644.]
 [  6308.]
 [ 12829.]
 [  8919.]
 [  7518.]
 [-10169.]
 [  8826.]
 [  7356.]
 [-10692.]
 [-10914.]
 [ 10167.]
 [  9240.]
 [  5418.]
 [ -9797.]
 [  4236.]
 [  8832.]
 [ -8663.]
 [-13527.]
 [  3511.]
 [-12831.]
 [  3936.]
 [ 12435.]
 [  7081.]
 [  -359.]
 [  7941.]
 [ 10925.]
 [-11755.]
 [  8034.]
 [ -6950.]
 [-17199.]
 [  7561.]
 [    81.]
 [ 11309.]
 [  7210.]
 [  8979.]
 [-11790.]
 [  3792.]
 [-11698.]
 [ -7812.]
 [  6228.]
 [-10606.]
 [ -7863.]
 [   728.]
 [ 15101.]
 [  6782.]
 [ 12805.]
 [  3403.]
 [  7887.]
 [ -6411.]
 [  5897.]
 [ -9399.]
 [-11513.]
 [ -7401.]
 [-14193.]
 [-12245.]
 [ -4504.]]
